// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (778531645)
#define NOTOSERIF_14_FONT_ID (-928381217)
#define NOTOSERIF_16_FONT_ID (17214534)
#define NOTOSERIF_18_FONT_ID (840051567)
#define NOTOSANS_12_FONT_ID (1597191560)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define UI_10_FONT_ID (1322569422)
#define UI_12_FONT_ID (1831230762)
#define SMALL_FONT_ID (1465627787)
#define CHINESE_CHESS_FONT_ID (1005290636)
#define CONTROL_18_FONT_ID (29318789)

// JRB OS reader fonts embedded in the application image (MiSans, GB2312
// Lv1+Lv2 full coverage, DEFLATE-compressed 2-bit bitmaps). These close the
// gap left by BUILTIN_READER_POINT_SIZES == {12} in the upstream build: the
// reader no longer needs an SD-card .cpfont for the 20pt default size.
// IDs are SHA256-derived exactly like build-font-ids.sh (Ruby text-mode read
// normalises CRLF to LF before hashing), so regenerating the headers with an
// unchanged pipeline keeps them stable.
#define MISANS_12_FONT_ID (543479311)
#define MISANS_20_FONT_ID (1489431786)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHINESE_CHESS_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CONTROL_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(MISANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(MISANS_20_FONT_ID != 0, "Font ID collision with sentinel");
